### ISSUE TITLE
Price slider has only one boundary

### ISSUE THREAD

**Issue by romainruaud** [Elastic-Suite/gally-sylius-connector#4]
**Gally Platform version(s) affected**: 1.2.x

The title says it all, the price filter is not usable out-of-the-box because it has only one bound :)

Btw, that's the same on the "Example application" that is shipped with Gally.

**Comment by shochdoerfer** [comment]
Thanks for the feedback Romain. I would not call the price filter unusable, but I fully get your point, it could work better :)

The challenge is: Sylius is currently using Semantic UI as CSS framework and uses jQuery as Javascript library. Neither supports slider elements out of the box. Since the front office filters are basically the ones from the Sylius Admin, they are quite limited in their capabilities. That's why I picked the HTML range input to at least have some basic slider functionality available. Sadly, the HTML range input does not support 2 slider handles out of the box. I found some very hackish solutions where 2 range input elements were combined to simulate 2 slider handles, but the demo did not work properly for me.

We could either rely on jQuery UI and it's slider component or use [this "native" Javascript solution](https://medium.com/@predragdavidovic10/native-dual-range-slider-html-css-javascript-91e778134816) I found this morning. I'll check what's possible and report back.

**Comment by shochdoerfer** [comment]
I couldn't get the "native" solution running with Sylius, and since I think jQuery UI is a bit too fat for "just" the slider component, I was checking other options and found this one: https://refreshless.com/nouislider/

Adding it to Sylius front office was easy, I just need to figure out how to best pass the data back and forth:   
![slider](https://github.com/Elastic-Suite/gally-sylius-connector/assets/596449/8156beff-5b8e-4db8-94f2-cff7064fcac6)

The good thing is that we can ship the dist js & CSS files with our plugin. If developers want to add the library to their frontend stack and web pack compile everything, that should also be possible. I think this gives the best flexibility. Maybe also a dependency you could add to the Example application if that feature is missing there as well.
